### ISSUE TITLE
Site in maintenance, alternative URL for API key

### ISSUE THREAD

**Issue by bbaassssiiee** [kbrebanov/ansible-virtualbox#1]
Today the web page https://www.virtualbox.org/ is currently down for maintenance.

You can also download API key directly from the VirtualBox download server.
So this one: http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
Instead of:   https://www.virtualbox.org/download/oracle_vbox.asc

**Comment by kbrebanov** [comment]
Thanks for this. I merged in your changes.
