### ISSUE TITLE
virtualbox_packages not known

### ISSUE THREAD

**Issue by leocrawford** [kbrebanov/ansible-virtualbox#6]
Hi,

It appears that the package to be installed is 'virtualbox_packages'. However this no longer seems to exist. Correcting to simply 'virtualbox' works fine.

`failed: [desktop] (item=[u'virtualbox_packages']) => {"changed": false, "item": ["virtualbox_packages"], "msg": "No package matching 'virtualbox_packages' is available"}`

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
